const inventario = [
    { id: 1, categoria: "calzado", nombre: "Bota P.U Negra sin Puntera", precio: "" },
    { id: 2, categoria: "calzado", nombre: "Bota P.U Negra con Puntera", precio: "" },
    { id: 3, categoria: "calzado", nombre: "Bota P.U Café sin Puntera", precio: "" },
    { id: 4, categoria: "calzado", nombre: "Bota P.U Café con Puntera", precio: "" },
    { id: 5, categoria: "calzado", nombre: "Bota Robusta RAIDER Negra", precio: "" },
    { id: 6, categoria: "calzado", nombre: "Bota Robusta RAIDER Café", precio: "" },
    { id: 7, categoria: "calzado", nombre: "Bota Walter Biker Negra Dama sin Puntera", precio: "" },
    { id: 8, categoria: "calzado", nombre: "Bota Walter Biker Café Dama sin Puntera", precio: "" },
    { id: 9, categoria: "calzado", nombre: "Bota Café Dieléctrica 3025", precio: "" },
    { id: 10, categoria: "calzado", nombre: "Bota ORO de seguridad sin Puntera", precio: "" },
    { id: 11, categoria: "calzado", nombre: "Bota Robusta RAIDER NEGRA / ORO DAMA SIN PUNTERA", precio: "" },
    { id: 12, categoria: "calzado", nombre: "Bota Robusta TROOPER Negra", precio: "" },
    { id: 13, categoria: "calzado", nombre: "Bota Robusta TROOPER Blanca", precio: "" },
    { id: 14, categoria: "calzado", nombre: "Bota Robusta TROOPER Café", precio: "" },
    { id: 15, categoria: "calzado", nombre: "Bota Steel REVOLUTIÓN DAMA FUCSIA", precio: "" },
    { id: 16, categoria: "calzado", nombre: "Bota Steel REVOLUTIÓN HOMBRE AZUL", precio: "" },
    { id: 17, categoria: "calzado", nombre: "Bota Steel REVOLUTIÓN HOMBRE NEGRA", precio: "" },
    { id: 18, categoria: "calzado", nombre: "Steel Series Bota Ingeniera DAMA", precio: "" },
    { id: 19, categoria: "calzado", nombre: "Botín Operador SAGA 2022E", precio: "" },
    { id: 20, categoria: "calzado", nombre: "Botín SAGA Hombre 4059", precio: "" },
    { id: 21, categoria: "calzado", nombre: "Botín SAGA Mujer 4059W", precio: "" },
    { id: 22, categoria: "calzado", nombre: "Bota Caña Alta SAGA 3046", precio: "" },
    { id: 23, categoria: "calzado", nombre: "Bota Tipo Soldador MASTER Café", precio: "" },
    { id: 24, categoria: "calzado", nombre: "Bota Wellington Caña Alta 8607 Amarilla", precio: "" },
    { id: 25, categoria: "calzado", nombre: "Bota Wellington Caña Alta 8679", precio: "" },
    { id: 26, categoria: "calzado", nombre: "Bota Wellington Caña Alta 8607", precio: "" },
    { id: 27, categoria: "calzado", nombre: "Bota Tennis Westland 9007", precio: "" },
    { id: 28, categoria: "calzado", nombre: "KONDOR Bota Jumbo Dieléctrica", precio: "" },
    { id: 29, categoria: "calzado", nombre: "KONDOR Bota Seguridad Dakar", precio: "" },
    { id: 30, categoria: "calzado", nombre: "Bota Lisa sin Puntera", precio: "" },
    { id: 31, categoria: "calzado", nombre: "Bota HOMBRE KS3280-NEG", precio: "" },
    { id: 32, categoria: "calzado", nombre: "Bota HOMBRE KS3280-CAF", precio: "" },
    { id: 33, categoria: "calzado", nombre: "BRAHMA Bota MUJER 0M2676-NEG", precio: "" },
    { id: 34, categoria: "calzado", nombre: "Bota MUJER BRAHMA OM2676-CAF", precio: "" },
    { id: 35, categoria: "calzado", nombre: "Bota BRAHMA Waterproof Negra", precio: "" },
    { id: 36, categoria: "calzado", nombre: "Bota BRAHMA Waterproof Cafe", precio: "" },
    { id: 37, categoria: "calzado", nombre: "Valeta Fina EJECUTIVA en cuero Negra / Blanca", precio: "" },
    { id: 38, categoria: "calzado", nombre: "Zapato de Tacón Clásico Dama", precio: "" },
    { id: 39, categoria: "calzado", nombre: "Zapato Clásico Hombre", precio: "" },
    { id: 40, categoria: "calzado", nombre: "Bota infantil Quiker", precio: "" },
    { id: 41, categoria: "calzado", nombre: "Botín Campera", precio: "" },
    { id: 42, categoria: "calzado", nombre: "Bota Rebelde Azul TRACK", precio: "" },
    { id: 43, categoria: "calzado", nombre: "Bota Macha Alta Negro", precio: "" },
    { id: 44, categoria: "calzado", nombre: "Bota Royal Alta Blanca", precio: "" },
    { id: 45, categoria: "calzado", nombre: "Bota Workman Alta Blanco", precio: "" },
    { id: 46, categoria: "calzado", nombre: "Bota Workman Alta Amarillo", precio: "" },
    { id: 47, categoria: "calzado", nombre: "BOTA ARGYLL SAFETY", precio: "" },
    { id: 48, categoria: "calzado", nombre: "Bota Super Track / Robusta Con/sin puntera", precio: "" },
    { id: 49, categoria: "calzado", nombre: "Bota Super Track / Robusta NEGRA", precio: "" },
    { id: 50, categoria: "calzado", nombre: "Bota Super Track / Robusta AMARILLA", precio: "" },
    { id: 51, categoria: "calzado", nombre: "Bota Super Track / Robusta BLANCA", precio: "" },
    { id: 52, categoria: "calzado", nombre: "Sueco EVACOL 175 Económico", precio: "" },
    { id: 53, categoria: "calzado", nombre: "Sueco EVACOL 080 Fino", precio: "" },
    { id: 54, categoria: "calzado", nombre: "Tenis Deportivos con Costura NEGRO", precio: "" },
    { id: 55, categoria: "calzado", nombre: "Tenis Deportivos Con Puntera NEGRO", precio: "" },
    { id: 56, categoria: "calzado", nombre: "Tenis Deportivos Bota Alta NEGRO", precio: "" },
    { id: 57, categoria: "calzado", nombre: "Tenis Deportivos Negros FASHION", precio: "" },
    { id: 58, categoria: "calzado", nombre: "Bota MONTANA Maxter sin puntera", precio: "" },
    { id: 59, categoria: "calzado", nombre: "Bota MONTANA Maxter con puntera de acero", precio: "" },
    { id: 60, categoria: "calzado", nombre: "Bota ARRIERO sin puntera", precio: "" },
    { id: 70, categoria: "protección visual", nombre: "Gafas Aquiles AL 026 (Claro / Oscuro)", precio: "" },
    { id: 71, categoria: "protección visual", nombre: "Gafas Aquiles AL 026 Soldadura Oxicorte (Grado 3.0)", precio: "" },
    { id: 72, categoria: "protección visual", nombre: "Gafas Pandora GB 930014 (Claro / Oscuro / Amarillo)", precio: "" },
    { id: 73, categoria: "protección visual", nombre: "Gafas Atreo AL 247 (Claro)", precio: "" },
    { id: 74, categoria: "protección visual", nombre: "Gafas Poseidón TV 960395 Monolente (Claro / Oscuro)", precio: "" },
    { id: 75, categoria: "protección visual", nombre: "Gafas Dédalo AL 138 (Claro Espejado / Claro / Oscuro / Amarillo)", precio: "" },
    { id: 76, categoria: "protección visual", nombre: "Gafas Europa GB 9310 Pro (Oscuro / Claro)", precio: "" },
    { id: 77, categoria: "protección visual", nombre: "Gafas Hermes Revo GB 9398 (Rojo Espejado / Azul Espejado)", precio: "" },
    { id: 78, categoria: "protección visual", nombre: "Gafas Teseo AL 212 (Claro / Oscuro)", precio: "" },
    { id: 79, categoria: "protección visual", nombre: "Gafas Perseo Revo AL 078 (Rojo Espejado / Azul Espejado)", precio: "" },
    { id: 80, categoria: "protección visual", nombre: "Gafas Urano AL 099 (Claro Espejado / Claro / Oscuro)", precio: "" },
    { id: 81, categoria: "protección visual", nombre: "Gafas Electra GB 9405 (Claro / Oscuro)", precio: "" },
    { id: 82, categoria: "protección visual", nombre: "Gafas Minotauro Dieléctrica (Oscuro)", precio: "" },
    { id: 83, categoria: "protección visual", nombre: "Gafas Íficles AL 611 (Claro / Oscuro)", precio: "" },
    { id: 84, categoria: "protección visual", nombre: "Gafas Perseo AL 078 (Claro Espejado / Claro / Oscuro)", precio: "" },
    { id: 85, categoria: "protección visual", nombre: "Gafas Odiseo GB 9317 Antiestática (Claro / Oscuro)", precio: "" },
    { id: 86, categoria: "protección visual", nombre: "Gafas Atalanta (Compatible con Lentes Formulados)", precio: "" },
    { id: 87, categoria: "protección visual", nombre: "Gafas Dédalo RX Bifocal AL 138 (+1.50 a +3.00)", precio: "" },
    { id: 88, categoria: "protección visual", nombre: "Gafas Steelpro Spy Claro Antiempañante", precio: "" },
    { id: 89, categoria: "protección visual", nombre: "Gafas Steelpro Spy Gris Sin Antiempañante", precio: "" },
    { id: 90, categoria: "protección visual", nombre: "Gafas Steelpro Spy Gris Antiempañante", precio: "" },
    { id: 100, categoria: "protección manual", nombre: "Guantes Hilaza Sencillo", precio: "" },
    { id: 101, categoria: "protección manual", nombre: "Guantes Hilaza PVC", precio: "" },
    { id: 102, categoria: "protección manual", nombre: "Guante de Látex para Vidrio", precio: "" },
    { id: 103, categoria: "protección manual", nombre: "Guante Anti Corte Multiflex - Steelpro", precio: "" },
    { id: 104, categoria: "protección manual", nombre: "Guantes Zubiola Nitrilo Corrugado Azul", precio: "" },
    { id: 105, categoria: "protección manual", nombre: "Guantes Zubiola NY Rojo", precio: "" },
    { id: 106, categoria: "protección manual", nombre: "Guantes Hilaza Recubiertos en Látex Corrugado", precio: "" },
    { id: 107, categoria: "protección manual", nombre: "Guante KIM Convector Nylon/Poliéster", precio: "" },
    { id: 108, categoria: "protección manual", nombre: "Guantes KIM-Skady", precio: "" },
    { id: 109, categoria: "protección manual", nombre: "Guantes de Seguridad KIM - Febe Poliuretano", precio: "" },
    { id: 110, categoria: "protección manual", nombre: "Guantes KIM - Heka", precio: "" },
    { id: 111, categoria: "protección manual", nombre: "Guantes KIM - Hades", precio: "" },
    { id: 112, categoria: "protección manual", nombre: "Guantes KIM Corus Nitrilo", precio: "" },
    { id: 113, categoria: "protección manual", nombre: "Guantes KIM Corus Nitrilo Ride", precio: "" },
    { id: 114, categoria: "protección manual", nombre: "Guantes KIM Corus Nitrilo Liso", precio: "" },
    { id: 115, categoria: "protección manual", nombre: "Guantes KIM Anuke Nitrilo", precio: "" },
    { id: 116, categoria: "protección manual", nombre: "Guantes KIM Thot Nitrilo", precio: "" },
    { id: 117, categoria: "protección manual", nombre: "Guantes KIM Troya Látex", precio: "" },
    { id: 118, categoria: "protección manual", nombre: "Guantes Transparente de Polietileno", precio: "" },
    { id: 119, categoria: "protección manual", nombre: "Guantes Transparente de Vinilo / KIM Bennu Látex", precio: "" },
    { id: 120, categoria: "protección manual", nombre: "Guantes de Látex-Examen", precio: "" },
    { id: 121, categoria: "protección manual", nombre: "Guantes de Nitrilo-Calibre #6", precio: "" },
    { id: 122, categoria: "protección manual", nombre: "Guantes de Nitrilo Azul-Calibre #4", precio: "" },
    { id: 124, categoria: "protección manual", nombre: "Guantes Nitrilo Industrial con Resistencia Química", precio: "" },
    { id: 125, categoria: "protección manual", nombre: "Guantes Neptuno KIM - PVC con Manga", precio: "" },
    { id: 126, categoria: "protección manual", nombre: "Guante Nitrilo Solvex Largo", precio: "" },
    { id: 127, categoria: "protección manual", nombre: "Guante Industrial Mosquetero Largo", precio: "" },
    { id: 128, categoria: "protección manual", nombre: "Guantes de Seguridad KIM-Aura Material Nitrilo", precio: "" },
    { id: 129, categoria: "protección manual", nombre: "Guante Industrial Nitrilo", precio: "" },
    { id: 130, categoria: "protección manual", nombre: "Guante Industrial Calibre 35", precio: "" },
    { id: 131, categoria: "protección manual", nombre: "Guantes Vaqueta Corto Sencillo", precio: "" },
    { id: 132, categoria: "protección manual", nombre: "Guantes Vaqueta Corto Reforzado en Vaqueta", precio: "" },
    { id: 133, categoria: "protección manual", nombre: "Guantes Vaqueta Largo Reforzado en Vaqueta", precio: "" },
    { id: 134, categoria: "protección manual", nombre: "Guantes Carnaza Corto Sencillo", precio: "" },
    { id: 135, categoria: "protección manual", nombre: "Guantes Carnaza Largo Reforzado en Carnaza", precio: "" },
    { id: 136, categoria: "protección manual", nombre: "Guantes Carnaza Zubi-Ola, Kodiak Para Soldar Largo", precio: "" },
    { id: 137, categoria: "protección manual", nombre: "Guante Soldador KIM-Hércules", precio: "" },
    { id: 138, categoria: "protección manual", nombre: "Guantes Soldador Vulcano Carnaza", precio: "" },
    { id: 139, categoria: "protección manual", nombre: "Guantes Hornero Carnaza Reforzado / Carnaza", precio: "" },
    { id: 140, categoria: "protección manual", nombre: "Guantes de Lona Tipo Petrolero (Cuñero)", precio: "" },
    { id: 141, categoria: "protección manual", nombre: "Guantes Hycron en Lona y Nitrilo", precio: "" },
    { id: 142, categoria: "protección manual", nombre: "Guante Hycron Tela-Goma Ferrawyy", precio: "" },
    { id: 143, categoria: "protección manual", nombre: "Guantes de Seguridad Nitrilo - Ares", precio: "" },
    { id: 144, categoria: "protección manual", nombre: "Guante ActivArmr® 80-100 - Ansell", precio: "" },
    { id: 145, categoria: "protección manual", nombre: "Guante Anti Impacto y Anti Corte Delta Plus Eos Nocut VV910", precio: "" },
    { id: 146, categoria: "protección manual", nombre: "Guantes Ironclad Kong", precio: "" },
    { id: 147, categoria: "protección manual", nombre: "Guante Poliéster Link Tech", precio: "" },
    { id: 150, categoria: "impermeables", nombre: "Conjunto Impermeable Motociclista Calibre 18", precio: "" },
    { id: 151, categoria: "impermeables", nombre: "Poncho/Carpa Impermeable en PVC Calibre 16", precio: "" },
    { id: 152, categoria: "impermeables", nombre: "Delantal en PVC Calibre 18 / Calibre 25 / Extrafino (Polietileno)", precio: "" },
    { id: 153, categoria: "impermeables", nombre: "Delantal en PVC Calibre 18 con Refuerzo Abdominal", precio: "" },
    { id: 154, categoria: "impermeables", nombre: "Conjunto Impermeable Fontanero sin Botas Calibre 18", precio: "" },
    { id: 155, categoria: "impermeables", nombre: "Impermeable Fontanero con Botas Calibre 18", precio: "" },
    { id: 156, categoria: "impermeables", nombre: "Overol Escafandra Impermeable con Botas y Guantes Calibre 18", precio: "" },
    { id: 170, categoria: "primeros auxilios", nombre: "Botiquín Térmico 18 Elementos", precio: "" },
    { id: 171, categoria: "primeros auxilios", nombre: "Botiquín Bolso Terciar al Hombro (Sin Elementos)", precio: "" },
    { id: 172, categoria: "primeros auxilios", nombre: "Ambulancia Pequeño Botiquín (Sin Elementos)", precio: "" },
    { id: 173, categoria: "primeros auxilios", nombre: "Botiquín Petrolero al Hombro (Sin Elementos)", precio: "" },
    { id: 174, categoria: "primeros auxilios", nombre: "Botiquín Petrolero de Espalda (Sin Elementos)", precio: "" },
    { id: 175, categoria: "primeros auxilios", nombre: "Bolso Botiquín Ambulancia Grande (Sin Elementos)", precio: "" },
    { id: 176, categoria: "primeros auxilios", nombre: "Extintores ABC Multipropósito", precio: "" },
    { id: 177, categoria: "primeros auxilios", nombre: "Extintor Solkaflan Agente Limpio 23 Flam 123", precio: "" },
    { id: 178, categoria: "primeros auxilios", nombre: "Extintor de Agua", precio: "" },
    { id: 179, categoria: "primeros auxilios", nombre: "Canastillas para Extintor", precio: "" },
    { id: 180, categoria: "primeros auxilios", nombre: "Soporte Pedestal Extintor", precio: "" },
    { id: 181, categoria: "primeros auxilios", nombre: "Soportes para Extintor y Camilla", precio: "" },
    { id: 182, categoria: "primeros auxilios", nombre: "Kit de Carretera", precio: "" },
    { id: 183, categoria: "primeros auxilios", nombre: "Kit Control Derrames 10 Galones en Bolso", precio: "" },
    { id: 184, categoria: "primeros auxilios", nombre: "Camilla Winner Verificada Emergencias", precio: "" },
    { id: 185, categoria: "primeros auxilios", nombre: "Cuello Thomas", precio: "" },
    { id: 186, categoria: "primeros auxilios", nombre: "Inmovilizador de Primeros Auxilios Tipo Trauma", precio: "" },
    { id: 187, categoria: "primeros auxilios", nombre: "Cuello Ortopédico Filadelfia", precio: "" },
    { id: 188, categoria: "primeros auxilios", nombre: "Silbato de Emergencia en Aluminio", precio: "" },
    { id: 189, categoria: "primeros auxilios", nombre: "Aro Salvavidas Acuático 55 cm", precio: "" },
    { id: 190, categoria: "primeros auxilios", nombre: "Chalecos Salvavidas Acuático", precio: "" },
    { id: 191, categoria: "primeros auxilios", nombre: "Linterna Super LED Recargable 2W", precio: "" },
    { id: 192, categoria: "primeros auxilios", nombre: "Linterna Super LED Recargable 3W", precio: "" },
    { id: 193, categoria: "primeros auxilios", nombre: "Linterna Super LED Recargable Cabeza 2W", precio: "" },
    { id: 194, categoria: "primeros auxilios", nombre: "Linterna Super LED Recargable 10W", precio: "" },
    { id: 200, categoria: "señalización", nombre: "Colombinas Señalización Naranja", precio: "" },
    { id: 201, categoria: "señalización", nombre: "Conos de Seguridad Vial", precio: "" },
    { id: 202, categoria: "señalización", nombre: "Barrera Plástica Vial Tipo Maletín Grande", precio: "" },
    { id: 203, categoria: "señalización", nombre: "Caneca Vial Tipo Cilindro", precio: "" },
    { id: 204, categoria: "señalización", nombre: "Policía Acostado Plástico", precio: "" },
    { id: 205, categoria: "señalización", nombre: "Pala Antichispa Desarmable en Polipropileno", precio: "" },
    { id: 206, categoria: "señalización", nombre: "Chaleco Reflectivo Tipo A (4 Cintas)", precio: "" },
    { id: 207, categoria: "señalización", nombre: "Chaleco Reflectivo Tipo B (2 Cintas)", precio: "" },
    { id: 208, categoria: "señalización", nombre: "Brazaletes de Señalización (Brigadista)", precio: "" },
    { id: 209, categoria: "señalización", nombre: "Paletas de Señalización Pare / Siga", precio: "" },
    { id: 210, categoria: "señalización", nombre: "Señal Punto de Encuentro", precio: "" },
    { id: 211, categoria: "señalización", nombre: "Calcomanía para Extintor Multipropósito", precio: "" },
    { id: 212, categoria: "señalización", nombre: "Avisos Peligro Carga Larga y Ancha", precio: "" },
    { id: 213, categoria: "señalización", nombre: "Señales Genéricas y Fotoluminiscentes Variadas", precio: "" },
    { id: 214, categoria: "señalización", nombre: "Señal de Advertencia Piso Húmedo", precio: "" },
    { id: 215, categoria: "señalización", nombre: "Cinta Señalización Peligro", precio: "" },
    { id: 216, categoria: "señalización", nombre: "Cinta Antideslizante (Negra / Fotoluminiscente)", precio: "" },
    { id: 217, categoria: "señalización", nombre: "Cinta Reflectiva para Prenda de Costura 1 Pulgada", precio: "" },
    { id: 218, categoria: "señalización", nombre: "Cinta Reflectiva para Prenda de Costura 2 Pulgadas", precio: "" },
    { id: 219, categoria: "señalización", nombre: "Cinta Reflectiva para Tela (Calor)", precio: "" },
    { id: 300, categoria: "uniformes dama", nombre: "Camisa Dama Oxford M/Larga", precio: "" },
    { id: 301, categoria: "uniformes dama", nombre: "Camisa Dama Clásica Turín M/Larga", precio: "" },
    { id: 302, categoria: "uniformes dama", nombre: "Camisa Dama Drill Twill", precio: "" },
    { id: 303, categoria: "uniformes dama", nombre: "Camisa Dama Drill Rak Lee-Lee", precio: "" },
    { id: 304, categoria: "uniformes dama", nombre: "Camisa Dama Charretera M/Corta", precio: "" },
    { id: 305, categoria: "uniformes dama", nombre: "Camisa Dama Ruchi M/Corta", precio: "" },
    { id: 306, categoria: "uniformes dama", nombre: "Camisa Dama Jean M/Larga", precio: "" },
    { id: 307, categoria: "uniformes dama", nombre: "Camisa Dama Jean con Reflectivo M/Larga", precio: "" },
    { id: 308, categoria: "uniformes dama", nombre: "Buso Dama Polux", precio: "" },
    { id: 309, categoria: "uniformes dama", nombre: "Buso Dama Lacoste", precio: "" },
    { id: 310, categoria: "uniformes dama", nombre: "Buso Deportivo Dama", precio: "" },
    { id: 311, categoria: "uniformes dama", nombre: "Polo Dama Polux M/Larga", precio: "" },
    { id: 312, categoria: "uniformes dama", nombre: "Buso Deportivo M/Larga Cuello Redondo", precio: "" },
    { id: 313, categoria: "uniformes dama", nombre: "Guerrera Chef Unisex", precio: "" },
    { id: 314, categoria: "uniformes dama", nombre: "Antifluido Dama Jogger", precio: "" },
    { id: 315, categoria: "uniformes dama", nombre: "Antifluido Dama Cuello en V", precio: "" },
    { id: 316, categoria: "uniformes dama", nombre: "Antifluido Dama Cremallera", precio: "" },
    { id: 317, categoria: "uniformes dama", nombre: "Antifluido Dama Estampado Cremallera", precio: "" },
    { id: 318, categoria: "uniformes dama", nombre: "Sudadera Antifluido", precio: "" },
    { id: 319, categoria: "uniformes dama", nombre: "Sudadera Perchada", precio: "" },
    { id: 320, categoria: "uniformes dama", nombre: "Sudadera Drill Camuflada", precio: "" },
    { id: 321, categoria: "uniformes dama", nombre: "Jeans Stretch Azul Oscuro Dama", precio: "" },
    { id: 322, categoria: "uniformes dama", nombre: "Pantalón Dama Estudio F", precio: "" },
    { id: 323, categoria: "uniformes dama", nombre: "Pantalón Dama Drill Stretch", precio: "" },
    { id: 324, categoria: "uniformes dama", nombre: "Pantalón Camuflado Dama", precio: "" },
    { id: 341, categoria: "alturas", nombre: "ARNÉS MULTIPROPOSITO ECO EN \"H\"", precio: "" },
    { id: 342, categoria: "alturas", nombre: "ESLINGA POSICIONAMIENTO REGULABLE-500843", precio: "" },
    { id: 343, categoria: "alturas", nombre: "ESLINGA POSICIONAMIENTO ECO-501064", precio: "" },
    { id: 344, categoria: "alturas", nombre: "ESLINGA EXPERT EN \"Y\" - 500842", precio: "" },
    { id: 345, categoria: "alturas", nombre: "ESLINGA DE RESTRICCIÓN Y DETENCIÓN REGULABLE-500841", precio: "" },
    { id: 346, categoria: "alturas", nombre: "PRETAL DE ALTURA DIELECTRICO - EPI", precio: "" },
    { id: 347, categoria: "alturas", nombre: "LINEA DE VIDA VERTICAL SIN GANCHO-14mm (10 METROS)", precio: "" },
    { id: 348, categoria: "alturas", nombre: "LINEA DE VIDA VERTICAL 16mm (10 METROS)", precio: "" },
    { id: 349, categoria: "alturas", nombre: "LINEA DE VIDA VERTICAL 16mm (50 METROS)", precio: "" },
    { id: 350, categoria: "alturas", nombre: "POLEA DOBLE DE BRIDAS EN ALUMINIO", precio: "" },
    { id: 351, categoria: "alturas", nombre: "FRENO ARESTADOR PARA CUERDAS 16mm", precio: "" },
    { id: 352, categoria: "alturas", nombre: "MOSQUETON TIPO D EN ACERO CON SEGURO", precio: "" },
    { id: 400, categoria: "uniformes hombre", nombre: "CAMISA HOMBRE OXFORD M/LARGA", precio: "" },
    { id: 401, categoria: "uniformes hombre", nombre: "CAMISA HOMBRE CLASICA TURIN M/LARGA", precio: "" },
    { id: 402, categoria: "uniformes hombre", nombre: "CAMISA HOMBRE VITRAL M/LARGA", precio: "" },
    { id: 403, categoria: "uniformes hombre", nombre: "CAMISA HOMBRE RAYAS ALGODON", precio: "" },
    { id: 404, categoria: "uniformes hombre", nombre: "CAMISA HOMBRE DRILL TWILL", precio: "" },
    { id: 405, categoria: "uniformes hombre", nombre: "CAMISA HOMBRE DRILL RAK LEE-LEE", precio: "" },
    { id: 406, categoria: "uniformes hombre", nombre: "CAMISA M/LARGA JEAN SENCILLA", precio: "" },
    { id: 407, categoria: "uniformes hombre", nombre: "CAMISA M/LARGA JEAN FINA", precio: "" },
    { id: 408, categoria: "uniformes hombre", nombre: "CAMISA M/LARGA JEAN CON REFLECTIVO", precio: "" },
    { id: 409, categoria: "uniformes hombre", nombre: "CHAQUETA JEAN SOLDADOR", precio: "" },
    { id: 410, categoria: "uniformes hombre", nombre: "BUSO HOMBRE LACOSTE", precio: "" },
    { id: 411, categoria: "uniformes hombre", nombre: "BUSO HOMBRE POLUX", precio: "" },
    { id: 412, categoria: "uniformes hombre", nombre: "BUSO STICHER ALGODON", precio: "" },
    { id: 413, categoria: "uniformes hombre", nombre: "BUSO HOMBRE POLUX MG LARGA", precio: "" },
    { id: 414, categoria: "uniformes hombre", nombre: "BUSO HOMBRE LACOSTE MG LARGA", precio: "" },
    { id: 415, categoria: "uniformes hombre", nombre: "BUSO DEPORTIVO M/LARGA CUELLO REDONDO", precio: "" },
    { id: 416, categoria: "uniformes hombre", nombre: "CAMIBUSO TERPEL", precio: "" },
    { id: 417, categoria: "uniformes hombre", nombre: "CAMISA HOMBRE MECANICA DRILL ML", precio: "" },
    { id: 418, categoria: "uniformes hombre", nombre: "CAMISA HOMBRE MECANICA DRILL MC", precio: "" },
    { id: 419, categoria: "uniformes hombre", nombre: "CAMISA MECANICA ANI", precio: "" },
    { id: 420, categoria: "uniformes hombre", nombre: "CHALECO DRILL 4 BOLSILLOS", precio: "" },
    { id: 421, categoria: "uniformes hombre", nombre: "CHALECO 6 BOLSILLOS", precio: "" },
    { id: 422, categoria: "uniformes hombre", nombre: "CHALECO ANTIFLUIDO", precio: "" },
    { id: 423, categoria: "uniformes hombre", nombre: "CHAQUETA ANTIFLUIDO M/L", precio: "" },
    { id: 424, categoria: "uniformes hombre", nombre: "CHAQUETA CUARTO FRIO ANTIFLUIDO", precio: "" },
    { id: 425, categoria: "uniformes hombre", nombre: "DELANTAL DRILL", precio: "" },
    { id: 426, categoria: "uniformes hombre", nombre: "DELANTAL ANTIFLUIDO", precio: "" },
    { id: 427, categoria: "uniformes hombre", nombre: "DELANTAL JEAN-PARRILLA", precio: "" },
    { id: 428, categoria: "uniformes hombre", nombre: "DELANTAL LARGO TIPO FALDÓN", precio: "" },
    { id: 429, categoria: "uniformes hombre", nombre: "BATA EN ANTIFLUIDO", precio: "" },
    { id: 430, categoria: "uniformes hombre", nombre: "BATA EN DACRÓN", precio: "" },
    { id: 431, categoria: "uniformes hombre", nombre: "ANTIFLUIDO HOMBRE CUELLO EN \"V\"", precio: "" },
    { id: 432, categoria: "uniformes hombre", nombre: "GUERRERA CHEF HOMBRE", precio: "" },
    { id: 433, categoria: "uniformes hombre", nombre: "SUDADERA ANTIFLUIDO", precio: "" },
    { id: 434, categoria: "uniformes hombre", nombre: "OVEROL EN ANTIFLUIDO", precio: "" },
    { id: 435, categoria: "uniformes hombre", nombre: "OVEROL EN DRILL", precio: "" },
    { id: 436, categoria: "uniformes hombre", nombre: "TRAJE TIVEK DESECHABLE", precio: "" },
    { id: 437, categoria: "uniformes hombre", nombre: "SUDADERA PERCHADA", precio: "" },
    { id: 438, categoria: "uniformes hombre", nombre: "SUDADERA DRILL CAMUFLADA", precio: "" },
    { id: 439, categoria: "uniformes hombre", nombre: "PANTALÓN CAMUFLADO HOMBRE R-ARMY", precio: "" },
    { id: 440, categoria: "uniformes hombre", nombre: "JEAN AZUL OSCURO RIGIDO", precio: "" },
    { id: 441, categoria: "uniformes hombre", nombre: "JEAN AZUL OSCURO STRETCH", precio: "" },
    { id: 442, categoria: "uniformes hombre", nombre: "JEAN AZUL OSCURO DIELECTRICO", precio: "" },
    { id: 443, categoria: "uniformes hombre", nombre: "JEAN AZUL OSCURO REFLECTIVO", precio: "" },
    { id: 444, categoria: "uniformes hombre", nombre: "PANTALÓN DRILL STRETCH", precio: "" },
    { id: 445, categoria: "uniformes hombre", nombre: "PANTALÓN CLASICO", precio: "" },
    { id: 446, categoria: "uniformes hombre", nombre: "PANTALÓN VIGILANTE", precio: "" },
    { id: 447, categoria: "uniformes hombre", nombre: "CINTURON EN CUERO", precio: "" },
    { id: 448, categoria: "uniformes hombre", nombre: "CORBATAS Y CORBATINES", precio: "" },
    { id: 449, categoria: "uniformes hombre", nombre: "ROPA INTERIOR MASCULINA", precio: "" },
    { id: 450, categoria: "uniformes hombre", nombre: "MEDIAS EN ALGODON", precio: "" },
    { id: 451, categoria: "uniformes hombre", nombre: "MEDIAS ECO - DAMA/HOMBRE", precio: "" },
    { id: 511, categoria: "protección personal", nombre: "Careta Facial Media Cara 6200 - 3M", precio: "" },
    { id: 510, categoria: "protección personal", nombre: "Máscara Facial Completa - 3M", precio: "" },
    { id: 512, categoria: "protección personal", nombre: "Careta Económica con Filtro Doble", precio: "" },
    { id: 513, categoria: "protección personal", nombre: "Careta Económica con Filtro Sencillo", precio: "" },
    { id: 514, categoria: "protección personal", nombre: "Filtro Rosado para Soldador 2097 - 3M", precio: "" },
    { id: 515, categoria: "protección personal", nombre: "Filtro para Vapores y Gases 6003 - 3M", precio: "" },
    { id: 516, categoria: "protección personal", nombre: "Filtro para Vapores y Gases 6006 - 3M", precio: "" },
    { id: 517, categoria: "protección personal", nombre: "Filtro para Partículas 7093B - 3M", precio: "" },
    { id: 518, categoria: "protección personal", nombre: "Retenedor de Filtro 501 - 3M", precio: "" },
    { id: 519, categoria: "protección personal", nombre: "Careta de Soldador Sencilla", precio: "" },
    { id: 520, categoria: "protección personal", nombre: "Careta de Soldador Inteligente (Sumo)", precio: "" },
    { id: 521, categoria: "protección personal", nombre: "Careta p/ Soldar Inteligente Estampada (Steelco)", precio: "" },
    { id: 522, categoria: "protección personal", nombre: "Careta de Protección Facial con Malla Plástica", precio: "" },
    { id: 523, categoria: "protección personal", nombre: "Careta de Esmerilar", precio: "" },
    { id: 524, categoria: "protección personal", nombre: "Tapabocas Acrílico Antiempañante Eco", precio: "" },
    { id: 525, categoria: "protección personal", nombre: "Tapabocas en Tela", precio: "" },
    { id: 526, categoria: "protección personal", nombre: "Tapaboca con Visera", precio: "" },
    { id: 527, categoria: "protección personal", nombre: "Tapaboca Industrial Negro", precio: "" },
    { id: 528, categoria: "protección personal", nombre: "Mascarilla Desechable / Tapabocas Latexport (50 unidades)", precio: "" },
    { id: 529, categoria: "protección personal", nombre: "Cachucha Chavo / Safari (Tela: Drill)", precio: "" },
    { id: 530, categoria: "protección personal", nombre: "Safari Tipo Chavo", precio: "" },
    { id: 531, categoria: "protección personal", nombre: "Safari Tipo Ninja", precio: "" },
    { id: 532, categoria: "protección personal", nombre: "Capuchón Tipo Ninja (Sencillo / Doble Faz)", precio: "" },
    { id: 533, categoria: "protección personal", nombre: "Gorra en Malla con Visera", precio: "" },
    { id: 534, categoria: "protección personal", nombre: "Gorro Cocina con Visera", precio: "" },
    { id: 535, categoria: "protección personal", nombre: "Gorro Pirata con Patrón", precio: "" },
    { id: 536, categoria: "protección personal", nombre: "Gorro Pirata", precio: "" },
    { id: 537, categoria: "protección personal", nombre: "Gorro Malla Negro", precio: "" },
    { id: 538, categoria: "protección personal", nombre: "Gorro Malla Latexport", precio: "" },
    { id: 539, categoria: "protección personal", nombre: "Gorro Monja Blanco Latexport", precio: "" },
    { id: 540, categoria: "protección personal", nombre: "Gorra Malla Publicidad", precio: "" },
    { id: 541, categoria: "protección personal", nombre: "Gorras Publicitaria en Acrílico - Drill", precio: "" },
    { id: 542, categoria: "protección personal", nombre: "Gorra Importada", precio: "" },
    { id: 543, categoria: "protección personal", nombre: "Casco Capitán Tipo 1 con Cremallera", precio: "" },
    { id: 544, categoria: "protección personal", nombre: "Casco de Alturas Steel Pro", precio: "" },
    { id: 545, categoria: "protección personal", nombre: "Casco Dieléctrico con Ratchet", precio: "" },
    { id: 546, categoria: "protección personal", nombre: "Casco Safari Dieléctrico", precio: "" },
    { id: 547, categoria: "protección personal", nombre: "Barbuquejos de Casco", precio: "" },
    { id: 548, categoria: "protección personal", nombre: "Protector Auditivo - 101 dBA - Insertar (3M)", precio: "" },
    { id: 549, categoria: "protección personal", nombre: "Protector Tritón - Copa - 85 dBA", precio: "" },
    { id: 551, categoria: "protección personal", nombre: "Protector Auditivo - 26 dBA - Diadema (Steelpro)", precio: "" },
    { id: 552, categoria: "protección personal", nombre: "Protector Auditivo - 29 dBA - Insertar (Zen 7)", precio: "" },
    { id: 553, categoria: "protección personal", nombre: "Protector Auditivo - 23 dBA - Diadema (Samurai)", precio: "" },
    { id: 554, categoria: "protección personal", nombre: "Protector Auditivo Tapa Oídos 3M (TaperFit 2)", precio: "" },
    { id: 555, categoria: "protección personal", nombre: "Tapaoídos Siliconado de Inserción - Caja", precio: "" },
    { id: 600, categoria: "higiene y aseo", nombre: "Limpiador Desinfectante Floral Full Fresh 3785 ml", precio: "" },
    { id: 601, categoria: "higiene y aseo", nombre: "Limpiador Desinfectante Lavanda Full Fresh 3785 ml", precio: "" },
    { id: 602, categoria: "higiene y aseo", nombre: "Limpiador Desinfectante Canela Full Fresh 3785 ml", precio: "" },
    { id: 603, categoria: "higiene y aseo", nombre: "Limpiador con Bicarbonato-Limón Máxima 5000 ml", precio: "" },
    { id: 604, categoria: "higiene y aseo", nombre: "Limpiador con Bicarbonato Agente X 1000 ml", precio: "" },
    { id: 605, categoria: "higiene y aseo", nombre: "Jabón Líquido Antibacterial Sibyla 3785 ml", precio: "" },
    { id: 606, categoria: "higiene y aseo", nombre: "Jabón Líquido Cremoso Sibyla 3785 ml", precio: "" },
    { id: 607, categoria: "higiene y aseo", nombre: "Jabón Líquido 3D 3000 ml", precio: "" },
    { id: 608, categoria: "higiene y aseo", nombre: "Jabón Cremoso Manos y Cuerpo Sybila 1000 ml", precio: "" },
    { id: 609, categoria: "higiene y aseo", nombre: "Detergente en Polvo Multiusos Sin Aroma PQP Profesional 20 Kg", precio: "" },
    { id: 610, categoria: "higiene y aseo", nombre: "Detergente en Polvo Multiusos Floral PQP Profesional 20 Kg", precio: "" },
    { id: 611, categoria: "higiene y aseo", nombre: "Jabón Lavaplatos con Glicerina Super Express 700g", precio: "" },
    { id: 612, categoria: "higiene y aseo", nombre: "Suavizante Desinfectante Full Fresh 3785 ml", precio: "" },
    { id: 613, categoria: "higiene y aseo", nombre: "Blanqueador Desinfectante Agente X 2000 ml", precio: "" },
    { id: 614, categoria: "higiene y aseo", nombre: "Ácido Muriático Desmanchador de Piso 3000 ml", precio: "" },
    { id: 615, categoria: "higiene y aseo", nombre: "Desengrasante Industrial 3000 ml", precio: "" },
    { id: 616, categoria: "higiene y aseo", nombre: "Desengrasante Multisuper Cítrica Pinto 500ml", precio: "" },
    { id: 617, categoria: "higiene y aseo", nombre: "Limpiavidrios Antiempañante Full Fresh 500 ml", precio: "" },
    { id: 618, categoria: "higiene y aseo", nombre: "Vinagre Limpiador Multiusos Full Fresh 3785 ml", precio: "" },
    { id: 619, categoria: "higiene y aseo", nombre: "Alcohol Fiamme 3785 ml", precio: "" },
    { id: 620, categoria: "higiene y aseo", nombre: "Spray Shampoo Muebles, Alfombras y Tapizados Full Fresh 500 ml", precio: "" },
    { id: 621, categoria: "higiene y aseo", nombre: "Shampoo Muebles, Alfombras y Tapizados Full Fresh 1000 ml", precio: "" },
    { id: 622, categoria: "higiene y aseo", nombre: "Spray Silicona Líquida Full Fresh 500 ml", precio: "" },
    { id: 623, categoria: "higiene y aseo", nombre: "Restaurador de Partes Negras Full Fresh 250 ml", precio: "" },
    { id: 624, categoria: "higiene y aseo", nombre: "Shampoo para Vehículos Auto Brillante Full Fresh 3785 ml", precio: "" },
    { id: 625, categoria: "higiene y aseo", nombre: "Shampoo Vehículos Auto Brillante Full Fresh 1000ml", precio: "" },
    { id: 626, categoria: "higiene y aseo", nombre: "Ambientador de Varitas Atracción Frutal x2 Full Fresh 80 ml", precio: "" },
    { id: 627, categoria: "higiene y aseo", nombre: "Ambientador de Varitas Tropical Paradise x2 Full Fresh 80 ml", precio: "" },
    { id: 628, categoria: "higiene y aseo", nombre: "Ambientador Eléctrico Líquido Canela Full Fresh 24 ml", precio: "" },
    { id: 629, categoria: "higiene y aseo", nombre: "Ambientador En Aerosol 7 en 1 Dulces Besos Full Fresh 400 ml", precio: "" },
    { id: 630, categoria: "higiene y aseo", nombre: "Ambientador En Aerosol 7 en 1 Frutos Rojos Full Fresh 400 ml", precio: "" },
    { id: 631, categoria: "higiene y aseo", nombre: "Esponja Multiusos Trabajo Pesado Pinto Und", precio: "" },
    { id: 632, categoria: "higiene y aseo", nombre: "Esponja Multiusos Ollas y Parrillas Pinto Und", precio: "" },
    { id: 633, categoria: "higiene y aseo", nombre: "Cepillo Tipo Plancha Full Fresh Und", precio: "" },
    { id: 634, categoria: "higiene y aseo", nombre: "Cepillo Diamante Full Fresh Und", precio: "" },
    { id: 635, categoria: "higiene y aseo", nombre: "Cepillo De Piso Zafiro con Banda Pinto Und", precio: "" },
    { id: 636, categoria: "higiene y aseo", nombre: "Escoba de Cerdas Duras para Calle Unid", precio: "" },
    { id: 637, categoria: "higiene y aseo", nombre: "Escoba IRIS Pinto Und", precio: "" },
    { id: 638, categoria: "higiene y aseo", nombre: "Escoba GIRASOL Pinto Und", precio: "" },
    { id: 639, categoria: "higiene y aseo", nombre: "Escoba ORQUIDEA Pinto Und", precio: "" },
    { id: 640, categoria: "higiene y aseo", nombre: "Escoba ECO Und", precio: "" },
    { id: 641, categoria: "higiene y aseo", nombre: "Escoba Fina Und", precio: "" },
    { id: 642, categoria: "higiene y aseo", nombre: "Escoba Bruja de Calle Und", precio: "" },
    { id: 643, categoria: "higiene y aseo", nombre: "Rastrillo Metálico Und", precio: "" },
    { id: 644, categoria: "higiene y aseo", nombre: "Rastrillo Plástico con Palo Und", precio: "" },
    { id: 645, categoria: "higiene y aseo", nombre: "Chupa para Baño de Cabo Plástico Und", precio: "" },
    { id: 646, categoria: "higiene y aseo", nombre: "Recogedor con Banda Solary Und", precio: "" },
    { id: 647, categoria: "higiene y aseo", nombre: "Cepillo Sanitario con Base Eco Elephant Und", precio: "" },
    { id: 648, categoria: "higiene y aseo", nombre: "Cepillo Sanitario sin Base Fuller Und", precio: "" },
    { id: 649, categoria: "higiene y aseo", nombre: "Trapeador de Algodón Pinto 270 g Aprox", precio: "" },
    { id: 650, categoria: "higiene y aseo", nombre: "Trapeador de Microfibra Pinto 300 g", precio: "" },
    { id: 651, categoria: "higiene y aseo", nombre: "Limpia Vidrios Cristal Extensible Pinto Und", precio: "" },
    { id: 652, categoria: "higiene y aseo", nombre: "Limpiador De Telaraña Und", precio: "" },
    { id: 653, categoria: "higiene y aseo", nombre: "Set de Paños en Microfibra Pinto 6 und", precio: "" },
    { id: 654, categoria: "higiene y aseo", nombre: "Plumero Arcoiris Pinto Und", precio: "" },
    { id: 655, categoria: "higiene y aseo", nombre: "Bolsas de Basura (Blanca, Negra y Verde)", precio: "" },
    { id: 700, categoria: "mascotas", nombre: "DOGURMET CACHORRO 3 CEREALES 350 G", precio: "" },
    { id: 701, categoria: "mascotas", nombre: "DOGURMET CACHORRO 3 CEREALES 1 KG", precio: "" },
    { id: 702, categoria: "mascotas", nombre: "DOGURMET CACHORRO 3 CEREALES 2 KG", precio: "" },
    { id: 703, categoria: "mascotas", nombre: "DOGURMET CACHORRO LECHE DESLACTOSADA 350 G", precio: "" },
    { id: 704, categoria: "mascotas", nombre: "DOGURMET CACHORRO LECHE DESLACTOSADA 1 KG", precio: "" },
    { id: 705, categoria: "mascotas", nombre: "DOGURMET CACHORRO LECHE DESLACTOSADA 2 KG", precio: "" },
    { id: 706, categoria: "mascotas", nombre: "DOGURMET PARRILLADA MIXTA 350 G", precio: "" },
    { id: 707, categoria: "mascotas", nombre: "DOGURMET PARRILLADA MIXTA 2 KG", precio: "" },
    { id: 708, categoria: "mascotas", nombre: "DOGURMET CARNE PARRILLA 350 G", precio: "" },
    { id: 709, categoria: "mascotas", nombre: "DOGURMET CARNE PARRILLA 1 KG", precio: "" },
    { id: 710, categoria: "mascotas", nombre: "DOGURMET CARNE PARRILLA 2 KG", precio: "" },
    { id: 711, categoria: "mascotas", nombre: "DOGURMET PAVO Y POLLO 350 G", precio: "" },
    { id: 712, categoria: "mascotas", nombre: "DOGURMET PAVO Y POLLO 1 KG", precio: "" },
    { id: 713, categoria: "mascotas", nombre: "DOGURMET PAVO Y POLLO 2 KG", precio: "" },
    { id: 714, categoria: "mascotas", nombre: "DOGURMET SALMON Y CARNE 350 G", precio: "" },
    { id: 715, categoria: "mascotas", nombre: "DOGURMET SALMON Y CARNE 1 KG", precio: "" },
    { id: 716, categoria: "mascotas", nombre: "DOGURMET SALMON Y CARNE 2 KG", precio: "" },
    { id: 717, categoria: "mascotas", nombre: "DONKAN CACHORRO 350 G", precio: "" },
    { id: 718, categoria: "mascotas", nombre: "DONKAN CACHORRO 1 KG", precio: "" },
    { id: 719, categoria: "mascotas", nombre: "DONKAN CACHORRO 2 KG", precio: "" },
    { id: 720, categoria: "mascotas", nombre: "DONKAN CARNE Y CEREALES 350 G", precio: "" },
    { id: 721, categoria: "mascotas", nombre: "DONKAN CARNE Y CEREALES 1 KG", precio: "" },
    { id: 722, categoria: "mascotas", nombre: "DONKAN CARNE Y CEREALES 2 KG", precio: "" },
    { id: 723, categoria: "mascotas", nombre: "CHUNKY ADULTO RAZA PEQUEÑA 500 G", precio: "" },
    { id: 724, categoria: "mascotas", nombre: "CHUNKY ADULTO RAZA PEQUEÑA 4 KG", precio: "" },
    { id: 725, categoria: "mascotas", nombre: "CHUNKY ADULTO RAZA PEQUEÑA 8 KG", precio: "" },
    { id: 726, categoria: "mascotas", nombre: "CHUNKY CACHORRO 4 KG", precio: "" },
    { id: 727, categoria: "mascotas", nombre: "CHUNKY CACHORRO 9 KG", precio: "" },
    { id: 728, categoria: "mascotas", nombre: "CHUNKY ADULTO 500 G", precio: "" },
    { id: 729, categoria: "mascotas", nombre: "CHUNKY ADULTO 4 KG", precio: "" },
    { id: 730, categoria: "mascotas", nombre: "RINGO CACHORRO ORIGINAL 1 KG", precio: "" },
    { id: 731, categoria: "mascotas", nombre: "RINGO CROQUETAS ORIGINAL 1 KG", precio: "" },
    { id: 732, categoria: "mascotas", nombre: "SUPERCAN CROQUETAS 30 KG", precio: "" },
    { id: 733, categoria: "mascotas", nombre: "SUPERCAN CROQUETAS 500 G", precio: "" },
    { id: 734, categoria: "mascotas", nombre: "SUPERCAN DELI CACHORRO 500 G", precio: "" },
    { id: 735, categoria: "mascotas", nombre: "FILPO ADULTO 10 KG", precio: "" },
    { id: 736, categoria: "mascotas", nombre: "FILPO ADULTO 30 KG", precio: "" },
    { id: 737, categoria: "mascotas", nombre: "BIRBO ADULTO MEDIANOS Y GRANDES 1 KG", precio: "" },
    { id: 738, categoria: "mascotas", nombre: "BIRBO RAZA PEQUEÑA 1 KG", precio: "" },
    { id: 739, categoria: "mascotas", nombre: "AGILITY GOLD PEQUEÑOS CACHORROS 1.5 KG", precio: "" },
    { id: 740, categoria: "mascotas", nombre: "AGILITY GOLD PEQUEÑOS ADULTOS 1.5 KG", precio: "" },
    { id: 741, categoria: "mascotas", nombre: "AGILITY GOLD GRANDES CACHORROS 1.5 KG", precio: "" },
    { id: 742, categoria: "mascotas", nombre: "AGILITY GOLD GRANDES ADULTOS 1.5 KG", precio: "" },
    { id: 743, categoria: "mascotas", nombre: "DOG CHOW CACHORRO RAZAS MEDIANAS Y GRANDES 475 G", precio: "" },
    { id: 744, categoria: "mascotas", nombre: "DOG CHOW CACHORRO RAZAS MEDIANAS Y GRANDES 1 KG", precio: "" },
    { id: 745, categoria: "mascotas", nombre: "DOG CHOW CACHORRO RAZAS MEDIANAS Y GRANDES 2 KG", precio: "" },
    { id: 746, categoria: "mascotas", nombre: "DOG CHOW CACHORRO RAZAS PEQUEÑAS Y MINIS 475 G", precio: "" },
    { id: 747, categoria: "mascotas", nombre: "DOG CHOW CACHORRO RAZAS PEQUEÑAS Y MINIS 1 KG", precio: "" },
    { id: 748, categoria: "mascotas", nombre: "DOG CHOW ADULTO RAZAS PEQUEÑAS Y MINIS 475 G", precio: "" },
    { id: 749, categoria: "mascotas", nombre: "DOG CHOW ADULTO RAZAS PEQUEÑAS Y MINIS 1 KG", precio: "" },
    { id: 750, categoria: "mascotas", nombre: "DOG CHOW ADULTO RAZAS PEQUEÑAS Y MINIS 2 KG", precio: "" },
    { id: 751, categoria: "mascotas", nombre: "DOG CHOW ADULTO RAZAS MEDIANAS Y GRANDES 475 G", precio: "" },
    { id: 752, categoria: "mascotas", nombre: "DOG CHOW ADULTO RAZAS MEDIANAS Y GRANDES 2 KG", precio: "" },
    { id: 753, categoria: "mascotas", nombre: "POUCH DOG CHOW ADULTO CON CARNE 100 G", precio: "" },
    { id: 754, categoria: "mascotas", nombre: "POUCH DOG CHOW ADULTO CON CORDERO 100 G", precio: "" },
    { id: 755, categoria: "mascotas", nombre: "POUCH PEDIGREE ADULTO CON CARNE 100 G", precio: "" },
    { id: 756, categoria: "mascotas", nombre: "POUCH PEDIGREE ADULTO RAZAS PEQUEÑAS CON CARNE 100 G", precio: "" },
    { id: 757, categoria: "mascotas", nombre: "MONELLO DOG RAZA PEQUEÑA 1 KG", precio: "" },
    { id: 758, categoria: "mascotas", nombre: "MONELLO DOG TRADICIONAL 1 KG", precio: "" },
    { id: 759, categoria: "mascotas", nombre: "DONKAT GATITOS 500 G", precio: "" },
    { id: 760, categoria: "mascotas", nombre: "DONKAT GATITOS 1 KG", precio: "" },
    { id: 761, categoria: "mascotas", nombre: "DONKAT ADULTOS 500 G", precio: "" },
    { id: 762, categoria: "mascotas", nombre: "DONKAT ADULTOS 1 KG", precio: "" },
    { id: 763, categoria: "mascotas", nombre: "MIRRINGO ADULTOS 500 G", precio: "" },
    { id: 764, categoria: "mascotas", nombre: "MIRRINGO ADULTOS 1 KG", precio: "" },
    { id: 765, categoria: "mascotas", nombre: "MIRRINGO ADULTOS 8 KG", precio: "" },
    { id: 766, categoria: "mascotas", nombre: "RAZAN BALSAMO PARA MASCOTAS 1000 ML", precio: "" },
    { id: 767, categoria: "mascotas", nombre: "RAZAN SHAMPOO PARA MASCOTAS 1000 ML", precio: "" },
    { id: 768, categoria: "mascotas", nombre: "RAZAN DESODORANTE ELIMINADOR DE OLORES PERROS MACHOS 200 ML", precio: "" },
    { id: 769, categoria: "mascotas", nombre: "RAZAN HOGAR LIMPIO, PERROS Y GATOS 200 ML", precio: "" },
];
